version: 2
jobs:
  build:
    docker:
      - image: circleci/5.6.36-apache-jessie-node-browsers
    steps:
      - checkout
      - run: date
  test:
    docker:
      - image: circleci/5.6.36-apache-jessie-node-browsers
    steps:
      - checkout
      - run: date
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
